name: Slack
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: hard-braking
    required: true
  - name: webhook_url
    inputType: FreeText
    description: The webhook url to send notifications to
    defaultValue: https://hooks.slack.com/services/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
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
